spring:
  jpa:
    database: mysql
    hibernate:
      show-sql: true
      dll-auto: update
      use-new-id-generator-mappings: false

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/logistics_db
    username: springuser
    password: passwd
    driver-class-name: com.mysql.jdbc.Driver
